export * from './wayPoint.interface';
export * from './flightDetail.interface';
export * from './flightPosition.interface';
export * from './flightFlifo.interface';
export * from './flightDetailProp.interface'
export * from './airport.interface'
export * from './icon.interface'
export * from './createFlightMarker.interface'
export * from './updateFlightMarker.interface'